feat: Automatic Pull Request from CI (#6)
* Create npm-publish-github-packages.yml

* devops

fixed actions

* update angular.json

update configuration for deploy

* fixed test

fixed some test for example

* add karma config

add karma config file

* some fixed

* fixed test

fixed config test in CI

* test

add some test for example

* fixed test

fixed sidebarcomponent test

* add secret

add sonar url secret

* Update actions.yml

update actions

* Update actions.yml

* code coverage

add code coverage report

* Update karma.conf.js

* Update karma.conf.js

* Update karma.conf.js

* fixed test

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update angular.json

* Update actions.yml

* Update actions.yml

* Update karma.conf.js

* karma config

* add testing dependency

* fixed karma config

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* fixd some bug

fixed some bug

* Update actions.yml

* add coverage

add more coverage

* Update permission.guard.spec.ts

* fixed test

fixed test coverage

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* Update actions.yml

* add new pipeline

add new pipeline to merge from release to main

* fix release cicd

fixed some errors about merge develop with release

* Update merge-main.yml

---------

Co-authored-by: Felipe Monzón <68126531+felipemonzon@users.noreply.github.com>
Co-authored-by: Felipe Monzón <felipemonzon2705@gmail.com>

diff --git a/.github/workflows/merge-main.yml b/.github/workflows/merge-main.yml
--- a/.github/workflows/merge-main.yml
+++ b/.github/workflows/merge-main.yml
@@ -44,8 +44,17 @@ jobs:
         run: npm install
 
       - name: Ejecutar pruebas
-        run: npm run test -- --no-watch --no-progress --code-coverage
+        run: npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessNoSandbox
 
+        # Paso de depuración: Lista los archivos en el directorio de trabajo
+      - name: Validar la existencia del informe de cobertura
+        run: |
+          if [ -f "coverage/archetype-dashboard-webapp/lcov.info" ]; then
+            echo "✅ ¡Informe de cobertura encontrado!"
+          else
+            echo "❌ Error: No se encontró el informe de cobertura lcov.info."
+            exit 1
+          fi
       - name: Análisis de SonarCloud
         if: success()
         uses: SonarSource/sonarqube-scan-action@v5
